version: '3'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./landing:/var/www/landing
      - ./activity:/var/www/activity
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "80:80"
      - "8080:8080"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./landing:/var/www/landing
      - ./activity:/var/www/activity
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./landing:/var/www/landing
      - ./activity:/var/www/activity
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    volumes:
      - ./docker/mysql/start.sql:/docker-entrypoint-initdb.d/start.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
